### ISSUE TITLE
خرابی قالب در بلاگ بیان − درصورت استفاده از تگ code در مطالب

### ISSUE THREAD

**Issue by alirezaahani** [asemanam-blog/pink-flower#1]
در بلاگ بیان اگر در مطلبی از تگ code که توسط خود ویرایشگر وارد میشود استفاده کنید ستون های قالب خراب میشوند :
http://s4.picofile.com/file/8397308542/screenshot_6e326970.jpg
http://s5.picofile.com/file/8397308626/screenshot_fe2760bd.jpg

**Comment by mimr9** [comment]
تشکر بابت گزارش، کد تصحیح و مشکل برطرف شد
